# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:

# Import torch
import torch


# Create random tensor
tensor0 = torch.rand(size=(7,7))

print(tensor0)


# Create random tensor


tensor([[0.9476, 0.5164, 0.5340, 0.6197, 0.9541, 0.3221, 0.7043],
        [0.6366, 0.3145, 0.7194, 0.0725, 0.5606, 0.8787, 0.8528],
        [0.4112, 0.0055, 0.7875, 0.4567, 0.9049, 0.3374, 0.6016],
        [0.4129, 0.6026, 0.7501, 0.2541, 0.5059, 0.4418, 0.0151],
        [0.4000, 0.8585, 0.4322, 0.2163, 0.6858, 0.1848, 0.8528],
        [0.6072, 0.7718, 0.9577, 0.0580, 0.5754, 0.9549, 0.6479],
        [0.0435, 0.8875, 0.3465, 0.2424, 0.1362, 0.3003, 0.4944]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor

tensor1 = torch.rand(size=(1,7))

# Perform matrix multiplication
Result = torch.matmul(tensor0,tensor1.T)

print(Result)


tensor([[2.1895],
        [1.6761],
        [1.4851],
        [1.1333],
        [1.9109],
        [1.8468],
        [1.2445]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
rand_tensor1 = torch.rand(size=(7,7))
rand_tensor2 = torch.rand(size=(1,7))

# Matrix multiply tensors
result = torch.matmul(rand_tensor1,rand_tensor2.T)

print(result)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
set = torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
 # Set random seed
set = torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device: ",device)

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)

print(tensor_A)
print(tensor_B)


Device:  cuda
tensor([[0.8579, 0.6870, 0.0051],
        [0.1757, 0.7497, 0.6047]], device='cuda:0')
tensor([[0.1100, 0.2121, 0.9704],
        [0.8369, 0.2820, 0.3742]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
result = torch.matmul(tensor_A,tensor_B.T)

print(result,result.shape)

tensor([[0.4927, 0.4193],
        [0.6820, 0.5228]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
max = torch.max(result)
print(max)

# Find min
min = torch.min(result)
print(min)



tensor(0.6820, device='cuda:0')
tensor(0.4193, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
arg_max = torch.argmax(result)
print(arg_max)

# Find arg min
arg_min = torch.argmin(result)
print(arg_min)


tensor(2, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [12]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(size=(1,1,1,10))

# Remove single dimensions
squeezed_tensor = torch.squeeze(random_tensor)

# Print out tensors and their shapes
print(random_tensor,random_tensor.shape)
print(squeezed_tensor,squeezed_tensor.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
